# Generated by Django 4.2.21 on 2025-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_rank_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
