# Generated by Django 4.2.21 on 2025-11-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_downloads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game10_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game10_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game10_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game10_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game1_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game1_name',
            field=models.CharField(default='BlackHydra', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game1_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game2_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game2_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game2_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game2_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game3_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game3_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game3_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game3_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game4_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game4_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game4_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game4_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game5_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game5_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game5_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game5_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game6_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game6_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game6_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game6_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game7_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game7_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game7_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game7_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game8_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game8_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game8_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game8_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game9_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game9_name',
            field=models.CharField(default='Coming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game9_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='game9_points',
            field=models.IntegerField(default=0),
        ),
    ]
