# Generated by Django 4.2.21 on 2025-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_points_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lesson10_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson2_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson3_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson4_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson5_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson6_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson7_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson8_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson9_points',
            field=models.IntegerField(default=0),
        ),
    ]
