# Generated by Django 4.2.26 on 2026-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_order_product_payment_order_product_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="raw_response",
        ),
        migrations.AddField(
            model_name="payment",
            name="admin_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_screenshots/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sender_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="trx_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
