# Generated by Django 4.2.26 on 2026-07-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_payment_raw_response_payment_admin_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(default="bKash Manual", max_length=30),
        ),
    ]
